name: assignment1-9062044-JayPatel-CI-CD

on:
  push:
    branches:
      - assignment1-9062044-JayPatel
      - develop
      - release
  pull_request:
    branches:
      - develop
      - release

env:
  DOCKER_IMAGE: prog8860-calculator
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  # ========== BUILD JOB ==========
  build:
    name: Build Application
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/release' && 'production' || 'dev' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: ./Assignment1
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify build success
        run: echo "Build completed successfully for branch ${{ github.ref_name }}"

  # ========== TEST JOB ==========
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ github.ref == 'refs/heads/release' && 'production' || 'dev' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run tests
        working-directory: ./Assignment1
        run: |
          echo "Running tests..."
          python -m unittest discover -s Unit_Test -p "test_*.py"

  # ========== DOCKER JOB ==========
  dockerize:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    environment: ${{ github.ref == 'refs/heads/release' && 'production' || 'dev' }}

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          TAG=${{ github.run_number }}
          docker build -t $DOCKERHUB_USERNAME/$DOCKER_IMAGE:$TAG ./Assignment1
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Trivy Security Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ github.run_number }}
          format: table
          severity: 'HIGH,CRITICAL'
          exit-code: '0'
          ignore-unfixed: true

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push $DOCKERHUB_USERNAME/$DOCKER_IMAGE:${{ github.run_number }}
          if [[ "${GITHUB_REF#refs/heads/}" == "release" ]]; then
            docker tag $DOCKERHUB_USERNAME/$DOCKER_IMAGE:${{ github.run_number }} $DOCKERHUB_USERNAME/$DOCKER_IMAGE:latest
            docker push $DOCKERHUB_USERNAME/$DOCKER_IMAGE:latest
          fi

  # ========== SUMMARY JOB ==========
  summary:
    name: CI/CD Summary
    runs-on: ubuntu-latest
    needs: dockerize
    steps:
      - run: |
          echo "Build, Test, and Docker Push completed successfully."
          echo "Image: $DOCKERHUB_USERNAME/$DOCKER_IMAGE:${{ github.run_number }}"
